### ISSUE TITLE
用 BibTeX 实现对 UTF-8 编码的中文进行排序？

### ISSUE THREAD

**Issue by zepinglee** [ustctug/gbt-7714-2015#4]
《标准》里规定 author-year 式参考文献表的中文文献可采用两种排序方式：1. 拼音-字顺 2. 笔画-笔顺；然而 Unicode 是按照《康熙字典》的部首-笔划数排序的，能否 BibTeX 提供的接口实现符合要求的排序（UTF-8）？

**Comment by leo-liu** [comment]
主流的 BibTeX 实现都不支持 Unicode，也不支持 locale 相关的排序。包括 TeX Live 和 MIKTeX 的实现。
BibTeX8 和 BibTeXU 都只是 8bit 实现。

听说有部分 Linux 发行版有 locale 支持的 BibTeX 实现，不过个人没用过。

在主流发行版中普遍可用的是 biber，由 Perl 开发，配合 `biblatex` 使用。[biblatex-caspervector](https://github.com/CasperVector/biblatex-caspervector) 用的是这个方案。不过 biber 与 `biblatex` 是紧耦合的。

否则就只能单独开发一个 BibTeX 的分支。个人觉得意义不大。

**Comment by zepinglee** [comment]
感谢指导，那就保持现在这样了

我对 biblatex 不熟，以后有需要的话再研究

**Comment by leo-liu** [comment]
随便说一句，因为 GB2312-80 的一级汉字部分（3755 常用字）是按拼音排序的，所以以前 `.bib` 文件用 GBK 编码保存，直接用老 BibTeX 处理，基本上就是按拼音排序的。

因而个人用的话，可以借助 iconv 转码之类的土办法完成排序。
