### ISSUE TITLE
参考文献信息不全时会自动补充内容

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/gbt-7714-2015#5]
引用的参考文献如果缺失某些信息，会出现[出版社不详]，[出版者不详]，[S.1.]等类似的内容

**Comment by zepinglee** [comment]
标准就是这样要求的啊？

**Comment by zepinglee** [comment]
你是说电子文献？

**Comment by liuhuimin** [comment]
抱歉，没留意消息，标准应该不会出现[S.1.][S.n.]这类信息吧？感觉这些信息如果没有应该是空着，我引用博士论文，里面夹着[出版社不详]，[出版者不详]

**Comment by seisman** [comment]
先提供这三样：参考文献的bib文件、文中的引用方式以及最终效果图，以方便别人理解并重复你的问题。

**Comment by liuhuimin** [comment]
文件在这里，里面有两个效果图，链接：http://pan.baidu.com/s/1o8eTGnC 密码：mxnc
bibtex文件是从Google学术导出的。
我用的USTC thesis v2.0模板，发现升级之前不会出现[S.n]和[出版社不详]，[出版者不详]等内容，但有[s.1.]

**Comment by zepinglee** [comment]
> 学 位 论 文:作者.授予年.题名[文献类型标志]:[博士/硕士].授予单位所在地:授予 单位,起-止页码.

**Comment by seisman** [comment]
这其实是Google scholar导出的bibtex有问题

**Comment by zepinglee** [comment]
https://github.com/Haixing-Hu/typesetting-standard/raw/master/图书、期刊、论文的编排/【GB:T%207714-2005】文后参考文献著录规则.pdf
看第8.4节

**Comment by zepinglee** [comment]
GB/T 要求的项目太多了，Google scholar 的 bib 信息不一定齐全

**Comment by zepinglee** [comment]
不要老是拿着旧的模板说事，好像旧的就符合标准一样

**Comment by liuhuimin** [comment]
好吧，哭，博士论文哪来的出版地，另外标准里18页 A.4节也和显示的不一样啊

**Comment by liuhuimin** [comment]
附录A.4节没涉及出版地和出版者

**Comment by zepinglee** [comment]
北 京 :北 京 大 学 数 学 学 院
Berkeley: Univ.ofCalifor- nia

**Comment by liuhuimin** [comment]
我错了
