### ISSUE TITLE
如何编译出用户手册？

### ISSUE THREAD

**Issue by wolfzhchk** [ustctug/gbt-7714-2015#6]
我以为可以通过latexmk -xelatex -shell-escape，从dtx文件编译出用户手册。但是我好像缺不少东西，ltxdoc文档中，fontspec命令中调用的字体好像我都没有……

**Comment by zepinglee** [comment]
呃……这是mac 系统自带的
我改一下吧

**Comment by zepinglee** [comment]
fixed in 0b04c12
其实这些文档都是 btxbst.doc 的，我还没怎么写我的文档

**Comment by zepinglee** [comment]
用 `make doc` 就可以编译文档

**Comment by wolfzhchk** [comment]
知道了，谢谢！
