### ISSUE TITLE
按照国标，作者姓应该全大写，名可用首字母大写

### ISSUE THREAD

**Issue by ctexlive** [ustctug/gbt-7714-2015#7]
刚用了下你的样式，发现你的姓只有首字母大写，比如Hou Jianguo 
标准： HOU Jianguo 或者 HOU J 
你的样式： Hou J
请修正下

**Comment by zepinglee** [comment]
《标准》只要求“用汉语拼音书写的人名，姓全大写”，然而没有办法判断是不是用拼音写的；所以采取了保持原样的办法，你可以自己改成大写的 HOU

**Comment by szsdk** [comment]
但《标准》所给的例子里，所有西文的姓都是大写的。

**Comment by zepinglee** [comment]
没错，我觉得全大写的太丑，所以在不违反规定的前提下保持现状

算了，我还是改成大写的吧

**Comment by zepinglee** [comment]
这个好蛋疼，姓名全大写，Jr 又有个小写……

**Comment by szsdk** [comment]
不知道BibTeX中是如何处理人名的，biblatex里famliy name，given name，prefix 和 suffix 是可以分开处理的。

**Comment by ywgATustcbbs** [comment]
虽然关闭了，但是还是想说一下，国标其实很不靠谱的，部分法语、德语等等带有重音符号的字母，人名里比较常见，正常情况下是无法自动转换大小写的，甚至有没有对应的大写或小写字母都是个问题。自动文献管理的话这部分会很坑。我遇到过这种情况，要么转换之后会丢失字形显示成方框，要么就是转换失败，一堆大写里边夹一个小写重音字母，很显眼，导致的结果就是参考文献列表特别难看。有时候的效果不如首字母大写方便和好看。

**Comment by ywgATustcbbs** [comment]
还有就是国标里边的汉语拼音的人名似乎是不允许缩写为首字母的。其实这参考文献部分大家做的都不好，不管是endnote还是bibtex。按照学校出版社的老师的说法，现在参考文献并不一定要完完全全符合国标，只要整体上看着格式统一一致，美观大方，一般没有人去扣大小写、缩写这些细节问题的。

**Comment by nanmu42** [comment]
辛苦了。

**Comment by zepinglee** [comment]
关于其他西文字母的问题，一种办法是用 {}  括起来，这样 bibtex 就不处理了，让用户手动处理。

2015 是允许缩写为首字母的。

PS 这个是给中文 TeX 社区通用的，我们 ustcthesis 用的还是比较合理的方案（保持大小写原样），跟这个不完全一样。

**Comment by ywgATustcbbs** [comment]
没来得及看新的国标……感觉改了不少地方

**Comment by zepinglee** [comment]
修改英文作者的大小写 a7a2314
