### ISSUE TITLE
Suffix前是否应加逗号

### ISSUE THREAD

**Issue by szsdk** [ustctug/gbt-7714-2015#8]
根据《标准》A.7[7]，suffix（如 Jr）前是有一个逗号的。

**Comment by zepinglee** [comment]
嗯，马上修改

**Comment by szsdk** [comment]
突然发现，实际上这还有一个小问题。《标准2005》中Jr后面是带点的，即Jr.，而《标准2015》中Jr后面是没有点的。（私以为还是带点会更符合英语习惯，并减少感官上的奇异。以为姓名的分隔也是用的“,”）

**Comment by zepinglee** [comment]
我还是按照 2015 的标准改吧

**Comment by szsdk** [comment]
恩，按照标准来总是没问题的。
